// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: subnet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LocationType defines where the subnet is located
type LocationType int32

const (
	LocationType_DATACENTER LocationType = 0
	LocationType_SITE       LocationType = 1
	LocationType_CLOUD      LocationType = 2
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "DATACENTER",
		1: "SITE",
		2: "CLOUD",
	}
	LocationType_value = map[string]int32{
		"DATACENTER": 0,
		"SITE":       1,
		"CLOUD":      2,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_subnet_proto_enumTypes[0].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_subnet_proto_enumTypes[0]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{0}
}

// Subnet represents a network subnet with all its properties
type Subnet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	LocationType  LocationType           `protobuf:"varint,6,opt,name=location_type,json=locationType,proto3,enum=ipam.LocationType" json:"location_type,omitempty"`
	CloudInfo     *CloudInfo             `protobuf:"bytes,7,opt,name=cloud_info,json=cloudInfo,proto3" json:"cloud_info,omitempty"`
	Details       *SubnetDetails         `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	Utilization   *UtilizationInfo       `protobuf:"bytes,9,opt,name=utilization,proto3" json:"utilization,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_subnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet.ProtoReflect.Descriptor instead.
func (*Subnet) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{0}
}

func (x *Subnet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subnet) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Subnet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subnet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Subnet) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Subnet) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_DATACENTER
}

func (x *Subnet) GetCloudInfo() *CloudInfo {
	if x != nil {
		return x.CloudInfo
	}
	return nil
}

func (x *Subnet) GetDetails() *SubnetDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Subnet) GetUtilization() *UtilizationInfo {
	if x != nil {
		return x.Utilization
	}
	return nil
}

func (x *Subnet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Subnet) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CloudInfo contains cloud provider specific information
type CloudInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInfo) Reset() {
	*x = CloudInfo{}
	mi := &file_subnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInfo) ProtoMessage() {}

func (x *CloudInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInfo.ProtoReflect.Descriptor instead.
func (*CloudInfo) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{1}
}

func (x *CloudInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CloudInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CloudInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// SubnetDetails contains calculated subnet properties
type SubnetDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Netmask       string                 `protobuf:"bytes,2,opt,name=netmask,proto3" json:"netmask,omitempty"`
	Wildcard      string                 `protobuf:"bytes,3,opt,name=wildcard,proto3" json:"wildcard,omitempty"`
	Network       string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Broadcast     string                 `protobuf:"bytes,6,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	HostMin       string                 `protobuf:"bytes,7,opt,name=host_min,json=hostMin,proto3" json:"host_min,omitempty"`
	HostMax       string                 `protobuf:"bytes,8,opt,name=host_max,json=hostMax,proto3" json:"host_max,omitempty"`
	HostsPerNet   int32                  `protobuf:"varint,9,opt,name=hosts_per_net,json=hostsPerNet,proto3" json:"hosts_per_net,omitempty"`
	IsPublic      bool                   `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetDetails) Reset() {
	*x = SubnetDetails{}
	mi := &file_subnet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetDetails) ProtoMessage() {}

func (x *SubnetDetails) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetDetails.ProtoReflect.Descriptor instead.
func (*SubnetDetails) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{2}
}

func (x *SubnetDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SubnetDetails) GetNetmask() string {
	if x != nil {
		return x.Netmask
	}
	return ""
}

func (x *SubnetDetails) GetWildcard() string {
	if x != nil {
		return x.Wildcard
	}
	return ""
}

func (x *SubnetDetails) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SubnetDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubnetDetails) GetBroadcast() string {
	if x != nil {
		return x.Broadcast
	}
	return ""
}

func (x *SubnetDetails) GetHostMin() string {
	if x != nil {
		return x.HostMin
	}
	return ""
}

func (x *SubnetDetails) GetHostMax() string {
	if x != nil {
		return x.HostMax
	}
	return ""
}

func (x *SubnetDetails) GetHostsPerNet() int32 {
	if x != nil {
		return x.HostsPerNet
	}
	return 0
}

func (x *SubnetDetails) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// UtilizationInfo tracks IP address usage
type UtilizationInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalIps           int32                  `protobuf:"varint,1,opt,name=total_ips,json=totalIps,proto3" json:"total_ips,omitempty"`
	AllocatedIps       int32                  `protobuf:"varint,2,opt,name=allocated_ips,json=allocatedIps,proto3" json:"allocated_ips,omitempty"`
	UtilizationPercent float32                `protobuf:"fixed32,3,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UtilizationInfo) Reset() {
	*x = UtilizationInfo{}
	mi := &file_subnet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilizationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilizationInfo) ProtoMessage() {}

func (x *UtilizationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilizationInfo.ProtoReflect.Descriptor instead.
func (*UtilizationInfo) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{3}
}

func (x *UtilizationInfo) GetTotalIps() int32 {
	if x != nil {
		return x.TotalIps
	}
	return 0
}

func (x *UtilizationInfo) GetAllocatedIps() int32 {
	if x != nil {
		return x.AllocatedIps
	}
	return 0
}

func (x *UtilizationInfo) GetUtilizationPercent() float32 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

// CreateSubnetRequest is used to create a new subnet
type CreateSubnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	LocationType  LocationType           `protobuf:"varint,5,opt,name=location_type,json=locationType,proto3,enum=ipam.LocationType" json:"location_type,omitempty"`
	CloudInfo     *CloudInfo             `protobuf:"bytes,6,opt,name=cloud_info,json=cloudInfo,proto3" json:"cloud_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubnetRequest) Reset() {
	*x = CreateSubnetRequest{}
	mi := &file_subnet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubnetRequest) ProtoMessage() {}

func (x *CreateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubnetRequest.ProtoReflect.Descriptor instead.
func (*CreateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSubnetRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CreateSubnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubnetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSubnetRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateSubnetRequest) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_DATACENTER
}

func (x *CreateSubnetRequest) GetCloudInfo() *CloudInfo {
	if x != nil {
		return x.CloudInfo
	}
	return nil
}

// CreateSubnetResponse returns the created subnet or error
type CreateSubnetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        *Subnet                `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubnetResponse) Reset() {
	*x = CreateSubnetResponse{}
	mi := &file_subnet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubnetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubnetResponse) ProtoMessage() {}

func (x *CreateSubnetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubnetResponse.ProtoReflect.Descriptor instead.
func (*CreateSubnetResponse) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSubnetResponse) GetSubnet() *Subnet {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *CreateSubnetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// ListSubnetsRequest is used to query subnets with filters
type ListSubnetsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LocationFilter      string                 `protobuf:"bytes,1,opt,name=location_filter,json=locationFilter,proto3" json:"location_filter,omitempty"`
	CloudProviderFilter string                 `protobuf:"bytes,2,opt,name=cloud_provider_filter,json=cloudProviderFilter,proto3" json:"cloud_provider_filter,omitempty"`
	SearchQuery         string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	Page                int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize            int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListSubnetsRequest) Reset() {
	*x = ListSubnetsRequest{}
	mi := &file_subnet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubnetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubnetsRequest) ProtoMessage() {}

func (x *ListSubnetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubnetsRequest.ProtoReflect.Descriptor instead.
func (*ListSubnetsRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{6}
}

func (x *ListSubnetsRequest) GetLocationFilter() string {
	if x != nil {
		return x.LocationFilter
	}
	return ""
}

func (x *ListSubnetsRequest) GetCloudProviderFilter() string {
	if x != nil {
		return x.CloudProviderFilter
	}
	return ""
}

func (x *ListSubnetsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListSubnetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubnetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListSubnetsResponse returns a list of subnets
type ListSubnetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnets       []*Subnet              `protobuf:"bytes,1,rep,name=subnets,proto3" json:"subnets,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubnetsResponse) Reset() {
	*x = ListSubnetsResponse{}
	mi := &file_subnet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubnetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubnetsResponse) ProtoMessage() {}

func (x *ListSubnetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubnetsResponse.ProtoReflect.Descriptor instead.
func (*ListSubnetsResponse) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubnetsResponse) GetSubnets() []*Subnet {
	if x != nil {
		return x.Subnets
	}
	return nil
}

func (x *ListSubnetsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListSubnetsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetSubnetRequest is used to retrieve a specific subnet
type GetSubnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubnetRequest) Reset() {
	*x = GetSubnetRequest{}
	mi := &file_subnet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnetRequest) ProtoMessage() {}

func (x *GetSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnetRequest.ProtoReflect.Descriptor instead.
func (*GetSubnetRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{8}
}

func (x *GetSubnetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSubnetResponse returns the requested subnet or error
type GetSubnetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        *Subnet                `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubnetResponse) Reset() {
	*x = GetSubnetResponse{}
	mi := &file_subnet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubnetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubnetResponse) ProtoMessage() {}

func (x *GetSubnetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubnetResponse.ProtoReflect.Descriptor instead.
func (*GetSubnetResponse) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubnetResponse) GetSubnet() *Subnet {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *GetSubnetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// UpdateSubnetRequest is used to update an existing subnet
type UpdateSubnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	LocationType  LocationType           `protobuf:"varint,6,opt,name=location_type,json=locationType,proto3,enum=ipam.LocationType" json:"location_type,omitempty"`
	CloudInfo     *CloudInfo             `protobuf:"bytes,7,opt,name=cloud_info,json=cloudInfo,proto3" json:"cloud_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubnetRequest) Reset() {
	*x = UpdateSubnetRequest{}
	mi := &file_subnet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubnetRequest) ProtoMessage() {}

func (x *UpdateSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubnetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubnetRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSubnetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSubnetRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *UpdateSubnetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubnetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSubnetRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateSubnetRequest) GetLocationType() LocationType {
	if x != nil {
		return x.LocationType
	}
	return LocationType_DATACENTER
}

func (x *UpdateSubnetRequest) GetCloudInfo() *CloudInfo {
	if x != nil {
		return x.CloudInfo
	}
	return nil
}

// UpdateSubnetResponse returns the updated subnet or error
type UpdateSubnetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        *Subnet                `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubnetResponse) Reset() {
	*x = UpdateSubnetResponse{}
	mi := &file_subnet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubnetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubnetResponse) ProtoMessage() {}

func (x *UpdateSubnetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubnetResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubnetResponse) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSubnetResponse) GetSubnet() *Subnet {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *UpdateSubnetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// DeleteSubnetRequest is used to delete a subnet
type DeleteSubnetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubnetRequest) Reset() {
	*x = DeleteSubnetRequest{}
	mi := &file_subnet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubnetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubnetRequest) ProtoMessage() {}

func (x *DeleteSubnetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubnetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubnetRequest) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSubnetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSubnetResponse confirms deletion or returns error
type DeleteSubnetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubnetResponse) Reset() {
	*x = DeleteSubnetResponse{}
	mi := &file_subnet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubnetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubnetResponse) ProtoMessage() {}

func (x *DeleteSubnetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubnetResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubnetResponse) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSubnetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSubnetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error represents a structured error response
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_subnet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_subnet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_subnet_proto_rawDescGZIP(), []int{14}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_subnet_proto protoreflect.FileDescriptor

const file_subnet_proto_rawDesc = "" +
	"\n" +
	"\fsubnet.proto\x12\x04ipam\"\x8d\x03\n" +
	"\x06Subnet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x127\n" +
	"\rlocation_type\x18\x06 \x01(\x0e2\x12.ipam.LocationTypeR\flocationType\x12.\n" +
	"\n" +
	"cloud_info\x18\a \x01(\v2\x0f.ipam.CloudInfoR\tcloudInfo\x12-\n" +
	"\adetails\x18\b \x01(\v2\x13.ipam.SubnetDetailsR\adetails\x127\n" +
	"\vutilization\x18\t \x01(\v2\x15.ipam.UtilizationInfoR\vutilization\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"^\n" +
	"\tCloudInfo\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"\xa2\x02\n" +
	"\rSubnetDetails\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\anetmask\x18\x02 \x01(\tR\anetmask\x12\x1a\n" +
	"\bwildcard\x18\x03 \x01(\tR\bwildcard\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1c\n" +
	"\tbroadcast\x18\x06 \x01(\tR\tbroadcast\x12\x19\n" +
	"\bhost_min\x18\a \x01(\tR\ahostMin\x12\x19\n" +
	"\bhost_max\x18\b \x01(\tR\ahostMax\x12\"\n" +
	"\rhosts_per_net\x18\t \x01(\x05R\vhostsPerNet\x12\x1b\n" +
	"\tis_public\x18\n" +
	" \x01(\bR\bisPublic\"\x84\x01\n" +
	"\x0fUtilizationInfo\x12\x1b\n" +
	"\ttotal_ips\x18\x01 \x01(\x05R\btotalIps\x12#\n" +
	"\rallocated_ips\x18\x02 \x01(\x05R\fallocatedIps\x12/\n" +
	"\x13utilization_percent\x18\x03 \x01(\x02R\x12utilizationPercent\"\xe4\x01\n" +
	"\x13CreateSubnetRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x127\n" +
	"\rlocation_type\x18\x05 \x01(\x0e2\x12.ipam.LocationTypeR\flocationType\x12.\n" +
	"\n" +
	"cloud_info\x18\x06 \x01(\v2\x0f.ipam.CloudInfoR\tcloudInfo\"_\n" +
	"\x14CreateSubnetResponse\x12$\n" +
	"\x06subnet\x18\x01 \x01(\v2\f.ipam.SubnetR\x06subnet\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ipam.ErrorR\x05error\"\xc5\x01\n" +
	"\x12ListSubnetsRequest\x12'\n" +
	"\x0flocation_filter\x18\x01 \x01(\tR\x0elocationFilter\x122\n" +
	"\x15cloud_provider_filter\x18\x02 \x01(\tR\x13cloudProviderFilter\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x81\x01\n" +
	"\x13ListSubnetsResponse\x12&\n" +
	"\asubnets\x18\x01 \x03(\v2\f.ipam.SubnetR\asubnets\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\x05error\x18\x03 \x01(\v2\v.ipam.ErrorR\x05error\"\"\n" +
	"\x10GetSubnetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x11GetSubnetResponse\x12$\n" +
	"\x06subnet\x18\x01 \x01(\v2\f.ipam.SubnetR\x06subnet\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ipam.ErrorR\x05error\"\xf4\x01\n" +
	"\x13UpdateSubnetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x127\n" +
	"\rlocation_type\x18\x06 \x01(\x0e2\x12.ipam.LocationTypeR\flocationType\x12.\n" +
	"\n" +
	"cloud_info\x18\a \x01(\v2\x0f.ipam.CloudInfoR\tcloudInfo\"_\n" +
	"\x14UpdateSubnetResponse\x12$\n" +
	"\x06subnet\x18\x01 \x01(\v2\f.ipam.SubnetR\x06subnet\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ipam.ErrorR\x05error\"%\n" +
	"\x13DeleteSubnetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x14DeleteSubnetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ipam.ErrorR\x05error\"\xc3\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\adetails\x18\x03 \x03(\v2\x18.ipam.Error.DetailsEntryR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*3\n" +
	"\fLocationType\x12\x0e\n" +
	"\n" +
	"DATACENTER\x10\x00\x12\b\n" +
	"\x04SITE\x10\x01\x12\t\n" +
	"\x05CLOUD\x10\x02B+Z)github.com/bananaops/ipam-bananaops/protob\x06proto3"

var (
	file_subnet_proto_rawDescOnce sync.Once
	file_subnet_proto_rawDescData []byte
)

func file_subnet_proto_rawDescGZIP() []byte {
	file_subnet_proto_rawDescOnce.Do(func() {
		file_subnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subnet_proto_rawDesc), len(file_subnet_proto_rawDesc)))
	})
	return file_subnet_proto_rawDescData
}

var file_subnet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_subnet_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_subnet_proto_goTypes = []any{
	(LocationType)(0),            // 0: ipam.LocationType
	(*Subnet)(nil),               // 1: ipam.Subnet
	(*CloudInfo)(nil),            // 2: ipam.CloudInfo
	(*SubnetDetails)(nil),        // 3: ipam.SubnetDetails
	(*UtilizationInfo)(nil),      // 4: ipam.UtilizationInfo
	(*CreateSubnetRequest)(nil),  // 5: ipam.CreateSubnetRequest
	(*CreateSubnetResponse)(nil), // 6: ipam.CreateSubnetResponse
	(*ListSubnetsRequest)(nil),   // 7: ipam.ListSubnetsRequest
	(*ListSubnetsResponse)(nil),  // 8: ipam.ListSubnetsResponse
	(*GetSubnetRequest)(nil),     // 9: ipam.GetSubnetRequest
	(*GetSubnetResponse)(nil),    // 10: ipam.GetSubnetResponse
	(*UpdateSubnetRequest)(nil),  // 11: ipam.UpdateSubnetRequest
	(*UpdateSubnetResponse)(nil), // 12: ipam.UpdateSubnetResponse
	(*DeleteSubnetRequest)(nil),  // 13: ipam.DeleteSubnetRequest
	(*DeleteSubnetResponse)(nil), // 14: ipam.DeleteSubnetResponse
	(*Error)(nil),                // 15: ipam.Error
	nil,                          // 16: ipam.Error.DetailsEntry
}
var file_subnet_proto_depIdxs = []int32{
	0,  // 0: ipam.Subnet.location_type:type_name -> ipam.LocationType
	2,  // 1: ipam.Subnet.cloud_info:type_name -> ipam.CloudInfo
	3,  // 2: ipam.Subnet.details:type_name -> ipam.SubnetDetails
	4,  // 3: ipam.Subnet.utilization:type_name -> ipam.UtilizationInfo
	0,  // 4: ipam.CreateSubnetRequest.location_type:type_name -> ipam.LocationType
	2,  // 5: ipam.CreateSubnetRequest.cloud_info:type_name -> ipam.CloudInfo
	1,  // 6: ipam.CreateSubnetResponse.subnet:type_name -> ipam.Subnet
	15, // 7: ipam.CreateSubnetResponse.error:type_name -> ipam.Error
	1,  // 8: ipam.ListSubnetsResponse.subnets:type_name -> ipam.Subnet
	15, // 9: ipam.ListSubnetsResponse.error:type_name -> ipam.Error
	1,  // 10: ipam.GetSubnetResponse.subnet:type_name -> ipam.Subnet
	15, // 11: ipam.GetSubnetResponse.error:type_name -> ipam.Error
	0,  // 12: ipam.UpdateSubnetRequest.location_type:type_name -> ipam.LocationType
	2,  // 13: ipam.UpdateSubnetRequest.cloud_info:type_name -> ipam.CloudInfo
	1,  // 14: ipam.UpdateSubnetResponse.subnet:type_name -> ipam.Subnet
	15, // 15: ipam.UpdateSubnetResponse.error:type_name -> ipam.Error
	15, // 16: ipam.DeleteSubnetResponse.error:type_name -> ipam.Error
	16, // 17: ipam.Error.details:type_name -> ipam.Error.DetailsEntry
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_subnet_proto_init() }
func file_subnet_proto_init() {
	if File_subnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subnet_proto_rawDesc), len(file_subnet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subnet_proto_goTypes,
		DependencyIndexes: file_subnet_proto_depIdxs,
		EnumInfos:         file_subnet_proto_enumTypes,
		MessageInfos:      file_subnet_proto_msgTypes,
	}.Build()
	File_subnet_proto = out.File
	file_subnet_proto_goTypes = nil
	file_subnet_proto_depIdxs = nil
}
